### PR TITLE
Mutuajoseph/tf 7 application setup

### PR DESCRIPTION
**Pull request by sinatra-ms**

### CODE REVIEW

**Review by Kalunge — APPROVED** [review]
The App set up looks good.

**Review by otsembo — APPROVED** [review]
@mutuajoseph Good job on the PR. Everything looks ready to go.

**Comment by Albert-Byrone** [comment]
The App setup looks good.

**Review by Albert-Byrone — APPROVED** [review]
The App setup looks good.

**Review by Albert-Byrone — APPROVED** [review]

**Review by Albert-Byrone — APPROVED** [review]
Nicely done

**Pull request merged**
